import { FINAL_LETTER } from '../data/finalLetter.js';
import { TextureFactory } from '../utils/TextureFactory.js';
import AudioManager from '../systems/AudioManager.js';
import { gameState } from '../config.js';

export default class EndingScene extends Phaser.Scene {
  constructor(){super('EndingScene');}
  create(){
    this.audioManager=new AudioManager(this);this.audioManager.playMusic('endingMusic');
    TextureFactory.createPlayerTexture(this);TextureFactory.createMateoTexture(this);
    this.cameras.main.fadeIn(650,12,6,22);this.makeBackdrop();this.makeRescue();
    const collected=gameState.memories||[],cards=['card1','card2','card3'];gameState.finalLetterUnlocked=cards.every(c=>collected.includes(c));gameState.secretUnlocked=collected.filter(x=>!cards.includes(x)).length>=5;gameState.achievements=[...new Set([...(gameState.achievements||[]),'Nuestra historia','Amor verdadero'])];
  }
  makeBackdrop(){this.add.image(640,360,'bg-romantic').setDisplaySize(1280,720).setTint(0xffd6c2);this.add.rectangle(640,360,1280,720,0x491b3a,.22);for(let i=0;i<42;i++){const p=this.add.ellipse(Math.random()*1280,Math.random()*650,3,7,i%2?0xff7eae:0xffd0dc,.65);this.tweens.add({targets:p,y:p.y+90,x:p.x+(Math.random()-.5)*100,angle:180,duration:2200+Math.random()*2200,repeat:-1});}}
  makeRescue(){
    const finalMateo=true;
    this.villain=this.add.image(1080,535,'pecho-final',7).setScale(.88).setDepth(7);
    this.time.delayedCall(100,()=>this.assertUniqueCinematicCharacters());
    this.paola=this.add.image(390,555,'paola-final',9).setScale(.9).setDepth(10);this.mateo=this.add.image(880,555,'mateo-final',1).setScale(.88).setDepth(8);
    this.bars=this.add.container(880,510).setDepth(12);const frame=this.add.rectangle(0,0,145,180,0x15131d,.18).setStrokeStyle(10,0x292631);this.bars.add(frame);for(let i=-2;i<=2;i++)this.bars.add(this.add.rectangle(i*28,0,7,170,0x302d3a).setStrokeStyle(2,0x706879));
    const crown=this.add.text(1080,585,'♛',{fontSize:'42px',color:'#e5bb5d'}).setAngle(28).setOrigin(.5);this.add.text(1080,630,'PECHO PALOMA: “No... no puede ser.”',{fontFamily:'monospace',fontSize:'14px',color:'#df9abc'}).setOrigin(.5);
    this.dialog=this.add.text(640,115,'PAOLA: “El amor no se roba.”',{fontFamily:'monospace',fontSize:'25px',color:'#fff0d2',align:'center',stroke:'#32172f',strokeThickness:5}).setOrigin(.5);
    this.time.delayedCall(1100,()=>{this.tweens.add({targets:this.bars,y:300,alpha:0,duration:900,ease:'Cubic.easeIn'});this.dialog.setText('La celda se abre...');for(let i=0;i<7;i++){const bird=this.add.text(830+i*28,390+(i%2)*30,'🕊',{fontSize:'22px'});this.tweens.add({targets:bird,x:1350,y:100-i*15,alpha:0,duration:1500+i*90,onComplete:()=>bird.destroy()});}});
    this.time.delayedCall(2300,()=>{this.dialog.setText('MATEO: “Sabía que vendrías.”');if(finalMateo)this.mateo.setFrame(2);this.tweens.add({targets:this.mateo,x:670,duration:1000,ease:'Sine.easeInOut'});});
    this.time.delayedCall(3500,()=>{this.dialog.setText('PAOLA: “Siempre.”');this.tweens.add({targets:this.paola,x:590,duration:700,ease:'Sine.easeInOut'});});
    this.time.delayedCall(4300,()=>{this.dialog.setText('Por nosotros.');this.paola.setFlipX(false);this.mateo.setFlipX(true);if(finalMateo)this.mateo.setFrame(4);for(let i=0;i<22;i++){const h=this.add.text(630+(Math.random()-.5)*150,500+Math.random()*80,Math.random()>.4?'♥':'🌹',{fontSize:`${14+Math.random()*18}px`,color:'#ff6fa8'}).setOrigin(.5).setDepth(20);this.tweens.add({targets:h,y:h.y-180,x:h.x+(Math.random()-.5)*80,alpha:0,duration:1300+Math.random()*800,onComplete:()=>h.destroy()});}this.time.delayedCall(1300,()=>this.showEnvelope());});
  }
  countVisibleCharacter(textureKey){return this.children.list.filter(o=>o.visible&&o.texture?.key===textureKey).length;}
  assertUniqueCinematicCharacters(){const expected=[['paola-final','Paola'],['mateo-final','Mateo']];expected.forEach(([key,name])=>{const count=this.countVisibleCharacter(key);if(count!==1)console.error(`[ENDING QA] ${name}: se esperaba 1 sprite visible y hay ${count}`);});}
  showEnvelope(){
    this.rescueOverlay=this.add.container(0,0).setDepth(100);const shade=this.add.rectangle(640,360,1280,720,0x090510,.9);const title=this.add.text(640,95,'TODAS LAS CARTAS REUNIDAS\n♥  ★  🌹  ✉  ◆\nCARTA FINAL DESBLOQUEADA',{fontFamily:'monospace',fontSize:'24px',color:'#ffe6aa',align:'center',lineSpacing:8,stroke:'#4e1c42',strokeThickness:5}).setOrigin(.5);const envelope=this.add.container(640,390).setScale(.3).setAlpha(0);const body=this.add.rectangle(0,0,380,225,0xf1d6aa).setStrokeStyle(8,0xbf6b72);const flap=this.add.triangle(0,-5,-184,-105,184,-105,0,75,0xe4bd8c).setStrokeStyle(4,0xbf6b72);const seal=this.add.text(0,45,'♥',{fontFamily:'monospace',fontSize:'48px',color:'#bd3b67'}).setOrigin(.5);const hint=this.add.text(0,155,'ABRIR CARTA',{fontFamily:'monospace',fontSize:'18px',color:'#fff',backgroundColor:'#79335e',padding:{x:18,y:9}}).setOrigin(.5);envelope.add([body,flap,seal,hint]);this.rescueOverlay.add([shade,title,envelope]);this.tweens.add({targets:envelope,scale:1,alpha:1,duration:600,ease:'Back.easeOut'});shade.setInteractive();let opened=false;const open=()=>{if(opened)return;opened=true;this.tweens.add({targets:flap,scaleY:-.25,y:-105,duration:380,onComplete:()=>this.showLetter()});};shade.once('pointerdown',open);this.input.keyboard.once('keydown-ENTER',open);this.input.keyboard.once('keydown-SPACE',open);
  }
  showLetter(){
    this.rescueOverlay.destroy();const layer=this.add.container(0,0).setDepth(110);const shade=this.add.rectangle(640,360,1280,720,0x090510,.92).setInteractive();const shadow=this.add.rectangle(650,370,700,540,0x000000,.35);const paper=this.add.rectangle(640,350,700,540,0xfff1d7).setStrokeStyle(7,0xd18a8b);const deco=this.add.text(640,105,'🌹  💌  🌹',{fontSize:'30px'}).setOrigin(.5);const letter=this.add.text(640,345,FINAL_LETTER,{fontFamily:'monospace',fontSize:'18px',color:'#51223b',align:'center',lineSpacing:8,wordWrap:{width:610}}).setOrigin(.5);const next=this.add.text(640,620,'CONTINUAR',{fontFamily:'monospace',fontSize:'18px',color:'#fff',backgroundColor:'#78305d',padding:{x:20,y:10}}).setOrigin(.5);layer.add([shade,shadow,paper,deco,letter,next]);layer.setScale(.85).setAlpha(0);this.tweens.add({targets:layer,scale:1,alpha:1,duration:420,ease:'Back.easeOut'});let done=false;const finish=()=>{if(done)return;done=true;layer.destroy();this.showCompleted();};shade.once('pointerdown',finish);this.input.keyboard.once('keydown-ENTER',finish);this.input.keyboard.once('keydown-SPACE',finish);
  }
  showCompleted(){
    const shade=this.add.rectangle(640,360,1280,720,0x13091d,.93).setDepth(120);const title=this.add.text(640,270,'♥ JUEGO COMPLETADO ♥\n\nEl amor siempre gana.',{fontFamily:'monospace',fontSize:'38px',color:'#ffe5af',align:'center',stroke:'#71254f',strokeThickness:7}).setOrigin(.5).setDepth(122);for(let i=0;i<65;i++){const p=this.add.text(Math.random()*1280,-30-Math.random()*500,['♥','🌹','★','✦'][i%4],{fontSize:`${12+Math.random()*18}px`,color:i%2?'#ff82b4':'#ffe39a'}).setDepth(121);this.tweens.add({targets:p,y:760,x:p.x+(Math.random()-.5)*170,angle:(Math.random()-.5)*240,duration:2800+Math.random()*2500,repeat:1,delay:Math.random()*900,onComplete:()=>p.destroy()});}const next=this.add.text(640,570,'CONTINUAR',{fontFamily:'monospace',fontSize:'20px',color:'#fff',backgroundColor:'#74315c',padding:{x:22,y:11}}).setOrigin(.5).setDepth(123).setInteractive({useHandCursor:true});const go=()=>{gameState.endingUnlocked=true;gameState.currentScene='SecretScene';localStorage.setItem('rescate-de-amor-save',JSON.stringify(gameState));this.cameras.main.fadeOut(650,8,4,18);this.time.delayedCall(670,()=>this.scene.start('SecretScene'));};next.once('pointerdown',go);this.input.keyboard.once('keydown-ENTER',go);this.input.keyboard.once('keydown-SPACE',go);
  }
}
