import BaseLevelScene from './BaseLevelScene.js?v=20260829-world-remaster-01';
import { createMateoCageRig } from '../utils/CageRig.js?v=20260826-cage-rig-35';

const routePlatforms=Array.from({length:18},(_,i)=>({x:[360,1160,760][i%3],y:3920-i*200,w:i%4===0?440:320,supported:false,...(i===4||i===10?{movingX:55,moveSpeed:.0011,movePhase:i}:{}),...(i===7||i===13?{movingY:24,moveSpeed:.001,movePhase:i}:{})}));
const platforms=[...routePlatforms];

export default class Level4Scene extends BaseLevelScene {
  constructor(){super('Level4Scene',{title:'NIVEL 4 · TORRE DEL CORAZÓN',objective:'Asciende y activa los tres corazones mágicos.',theme:'tower',background:'bg-tower-clean',width:1540,height:4300,spawn:{x:55,y:4010},music:'castleMusic',sky:'#080512',skyTop:0x080512,skyBottom:0x301332,ground:0x17131d,platform:0x352c3c,trim:0xd7a34f,accent:0xff4fa8,cleanArchitecture:true,
    groundSegments:[{start:0,end:1540,top:4100}],platforms,routeCount:18,sections:[{y:3900,label:'VESTÍBULO DE LA TORRE'},{y:3250,label:'ELEVADORES DEL CORAZÓN'},{y:2520,label:'INTERIOR DE LA AGUJA'},{y:1780,label:'BALCONES DEL VIENTO'},{y:1030,label:'EXTERIOR SOBRE EL REINO'},{y:440,label:'FARO DEL AMOR'}],
    enemies:[{x:790,y:3350,type:'soldier',platformIndex:3,health:4},{x:790,y:2940,type:'knight',platformIndex:5,health:7},{x:790,y:2520,type:'archer',platformIndex:7,health:5},{x:790,y:2110,type:'guardian',platformIndex:9,health:8},{x:790,y:1695,type:'mage',platformIndex:11,health:6},{x:790,y:1280,type:'knight',platformIndex:13,health:8},{x:790,y:870,type:'guardian',platformIndex:15,health:9},{x:790,y:560,type:'general',name:'GUARDIÁN DEL CORAZÓN',miniBoss:true,platformIndex:17,health:16}],collectibles:[{x:760,y:3230,type:'fragment8',memory:true},{x:900,y:3230,type:'rose'},{x:790,y:1580,type:'rose'},{x:760,y:1070,type:'fragment9',memory:true}],hazards:[],arenas:[],checkpoints:[],required:[],unlock:5,next:'Level5Scene',exit:{x:760,y:455},exitLabel:'PALACIO REAL'});}

  create(){super.create();this.player.jumpVelocity=-520;this.heartsActivated=0;this.beaconActivated=false;this.heartNodes=[{x:760,y:3230},{x:760,y:1790},{x:760,y:710}].map((p,i)=>{const node=this.add.image(p.x,p.y,'collectible-heart').setScale(2).setTint(0xff70b5).setDepth(32);this.tweens.add({targets:node,scale:2.25,alpha:.72,duration:650+i*100,yoyo:true,repeat:-1});return{...p,node,active:false};});this.heartPrompt=this.add.text(640,610,'E · ACTIVAR CORAZÓN MÁGICO',{fontFamily:'monospace',fontSize:'17px',color:'#fff5ce',backgroundColor:'#551c4d',padding:{x:12,y:7}}).setOrigin(.5).setScrollFactor(0).setDepth(1150).setVisible(false);this.input.keyboard.on('keydown-E',()=>this.activateHeart());this.makeTowerAtmosphere();this.makeMainElevator();this.uiManager.showMessage('LA CORRIENTE DE LA TORRE IMPULSA TUS SALTOS','#cce9ff',2200);}

  makeMainElevator(){this.elevatorStart=this.time.now+6000;this.elevatorLastY=4070;this.elevatorRoute=[{from:4070,to:3282,travel:14000,wait:6000},{from:3282,to:1842,travel:20000,wait:6000},{from:1842,to:762,travel:16000,wait:6000},{from:762,to:540,travel:8000,wait:0}];const elevator=this.createSurface({x:640,top:4057,width:1200,height:105,frame:3,kind:'platform'});this.mainElevatorRecord=elevator;this.mainElevatorArt=elevator.art.setDepth(19);this.mainElevator=elevator.collider;this.add.text(640,4042,'ASCENSOR DEL CORAZÓN',{fontFamily:'monospace',fontSize:'14px',color:'#ffe7b5',backgroundColor:'#3b1938',padding:{x:8,y:4}}).setOrigin(.5).setDepth(21).setName('elevator-label');}

  getElevatorY(time){let elapsed=Math.max(0,time-this.elevatorStart);for(let i=0;i<3;i++){const leg=this.elevatorRoute[i];if(elapsed<=leg.travel)return Phaser.Math.Linear(leg.from,leg.to,Phaser.Math.Clamp(elapsed/leg.travel,0,1));elapsed-=leg.travel;if(i<2){if(elapsed<=leg.wait)return leg.to;elapsed-=leg.wait;}}const guardianAlive=this.general?.active&&this.general.health>0;if(this.heartsActivated<3||guardianAlive){this.elevatorFinalStart=0;return 762;}if(!this.elevatorFinalStart)this.elevatorFinalStart=time;return Phaser.Math.Linear(762,540,Phaser.Math.Clamp((time-this.elevatorFinalStart)/8000,0,1));}

  makeTowerAtmosphere(){this.windBands=[{y:2350,minX:250,maxX:1290,force:72},{y:1320,minX:180,maxX:1360,force:-88}];}

  activateHeart(){const heart=this.heartNodes?.find(h=>!h.active&&this.onMainElevator&&Math.abs(this.player.y-h.y)<125&&Math.abs(this.player.x-this.mainElevator.x)<610);if(!heart)return;heart.active=true;this.heartsActivated++;heart.node.setTint(0xffef9e);this.particleManager.burst(heart.x,heart.y,0xff67b4,32,260);this.uiManager.showDialogueBubble('PAOLA',`Corazón mágico · ${this.heartsActivated}/3`,{x:640,y:430,duration:1500,width:470});if(this.heartsActivated===3)this.activateBeacon();}

  activateBeacon(){if(this.beaconActivated)return;this.beaconActivated=true;const beam=this.add.image(790,300,'environment-atlas',16).setDisplaySize(180,1100).setTint(0xff4fa8).setAlpha(0).setDepth(18);this.tweens.add({targets:beam,alpha:.92,displayWidth:300,duration:850,ease:'Cubic.easeOut'});this.cameras.main.flash(520,255,95,170);this.cameras.main.shake(450,.006);this.uiManager.showMessage('FARO DEL AMOR ACTIVADO','#ffd2eb',2300);this.time.delayedCall(1500,()=>this.showMateoCutaway());}

  showMateoCutaway(){this.physics.pause();const shade=this.add.rectangle(640,360,1280,720,0x080512,.88).setScrollFactor(0).setDepth(1400),rig=createMateoCageRig(this,640,385,{frame:1,depth:1402,cageScale:.72,mateoScale:.82,locked:true});rig.setScrollFactor(0);const sky=this.add.text(640,130,'EL FARO CRUZA EL CIELO SOBRE EL PALACIO',{fontFamily:'monospace',fontSize:'20px',color:'#ffb8dc',stroke:'#280d27',strokeThickness:4}).setOrigin(.5).setScrollFactor(0).setDepth(1403);this.time.delayedCall(600,()=>this.uiManager.showDialogueBubble('MATEO','Paola...',{x:640,y:470,duration:1800,width:350}));this.time.delayedCall(2500,()=>{shade.destroy();rig.destroy();sky.destroy();this.physics.resume();});}

  updateExitState(){if(!this.exitPoint||!this.player)return;const bossAlive=this.general?.active&&this.general.health>0;this.exitAvailable=this.heartsActivated===3&&!bossAlive;this.exitGroup.setVisible(true).setAlpha(this.exitAvailable?1:.3);this.exitLockedText.setVisible(!this.exitAvailable&&this.player.y<520).setText((this.heartsActivated||0)<3?`🔒 CORAZONES MÁGICOS · ${this.heartsActivated||0}/3`:'🔒 DERROTA AL GUARDIÁN DEL CORAZÓN');this.exitNearby=this.exitAvailable&&Phaser.Math.Distance.Between(this.player.x,this.player.y,this.exitPoint.x,this.exitPoint.y)<105;this.exitPrompt.setVisible(this.exitNearby&&!this.finishing);}

  update(time,delta){super.update(time,delta);if(!this.player||this.gameOver)return;if(this.mainElevator?.body){const y=this.getElevatorY(time),top=this.mainElevator.body.top;if(!this.onMainElevator&&time>=this.elevatorStart&&Math.abs(this.player.x-this.mainElevator.x)<600&&this.player.body.bottom>top-75&&this.player.body.bottom<top+90)this.onMainElevator=true;this.mainElevator.y=y;this.mainElevator.body.updateFromGameObject();this.mainElevatorArt.y=y-13;if(this.mainElevatorRecord)this.mainElevatorRecord.top=this.mainElevator.body.top;const label=this.children.getByName('elevator-label');if(label)label.y=y-28;if(this.onMainElevator&&Math.abs(this.player.x-this.mainElevator.x)<610){this.player.y+=this.mainElevator.body.top-this.player.body.bottom;this.player.body.velocity.y=0;this.player.body.updateFromGameObject();}this.elevatorLastY=y;}const heart=this.heartNodes?.find(h=>!h.active&&this.onMainElevator&&Math.abs(this.player.y-h.y)<125&&Math.abs(this.player.x-this.mainElevator.x)<610);this.heartPrompt?.setVisible(!!heart);if(Phaser.Input.Keyboard.JustDown(this.player.keys.E))this.activateHeart();const wind=this.windBands?.find(w=>Math.abs(this.player.y-w.y)<105&&this.player.x>w.minX&&this.player.x<w.maxX);if(wind&&!this.player.isGrounded)this.player.setVelocityX(this.player.body.velocity.x+wind.force*delta/1000);}
}
