const STATES=Object.freeze({IDLE:'IDLE',PATROL:'PATROL',DETECT:'DETECT',CHASE:'CHASE',REPOSITION:'REPOSITION',TELEGRAPH:'TELEGRAPH',ATTACK:'ATTACK',RECOVER:'RECOVER',HURT:'HURT',DEAD:'DEAD'});

export default class Enemy extends Phaser.Physics.Arcade.Sprite{
  constructor(scene,x,y,config={}){
    super(scene,x,y,`enemy-${config.type||'pigeon'}`);this.scene=scene;this.type=config.type||'pigeon';this.speed=config.speed||96;this.direction=config.direction||1;this.miniBoss=!!config.miniBoss;
    const baseHealth=config.health||3,level=Number(scene.scene.key.match(/\d+/)?.[0])||1,roleBonus={archer:.1,mage:.16,magic:.16,assassin:.22,knight:.28,guardian:.34,guard:.34,general:.4}[this.type]||0,healthScale=this.miniBoss?1.55+level*.1:1.7+(level-1)*.12+roleBonus,minimum={pigeon:4,winged:4,dive:4,soldier:5,archer:6,mage:7,magic:7,assassin:8,knight:9,guardian:10,guard:10,general:22}[this.type]||5;
    this.health=Math.max(minimum+Math.floor((level-1)*.75),Math.ceil(baseHealth*healthScale));this.maxHealth=this.health;this.requestedMinX=Number.isFinite(config.minX)?config.minX:null;this.requestedMaxX=Number.isFinite(config.maxX)?config.maxX:null;this.minX=config.minX??x-180;this.maxX=config.maxX??x+180;this.patrolMinX=this.minX;this.patrolMaxX=this.maxX;this.damage=config.damage||1;this.displayName=config.name||null;this.runeGuardian=!!config.runeGuardian;this.spawnX=x;this.safeSpawn={x,y};this.startY=y;this.flying=['pigeon','dive','magic','winged'].includes(this.type);this.humanoid=['guard','guardian','assassin','soldier','archer','knight','mage','general'].includes(this.type);this.ranged=['archer','mage','magic'].includes(this.type);this.state=STATES.IDLE;this.stateTime=260+Math.random()*280;this.attackCooldown=650+Math.random()*500;this.damageActive=false;this.attackFx=null;this.attackSlot=false;this.diveTarget=null;this.generalMove=0;this.aggroUntil=0;this.lastKnownPlayerX=x;this.alertFx=null;this.staggerCooldown=0;this.stepCooldown=0;
    scene.add.existing(this);scene.physics.add.existing(this);this.spriteRow={soldier:0,archer:0,assassin:1,mage:1,magic:1,knight:2,guardian:2,guard:2,general:3}[this.type];this.roleTint={archer:0xe7c39a,assassin:0xb69ad9,mage:0xd9b3ff,guardian:0xc8d6e8,knight:0xd7c18e}[this.type]||0xffffff;this.hasEnemySheet=this.spriteRow!==undefined&&scene.textures.exists('pigeon-enemies-v2');if(this.hasEnemySheet){this.setTexture('pigeon-enemies-v2',this.spriteRow*6);this.setScale(this.type==='general'?.82:.66);if(this.roleTint!==0xffffff)this.setTint(this.roleTint);}else this.setScale(this.type==='general'?1.25:this.humanoid?1.05:1.35);if(this.humanoid)this.body.setSize(this.hasEnemySheet?42:34,this.hasEnemySheet?70:58).setOffset(this.hasEnemySheet?43:8,this.hasEnemySheet?43:10);this.setCollideWorldBounds(true).setBounce(.05).setDepth(22);this.body.setAllowGravity(!this.flying);
    const barWidth=this.miniBoss?70:48,bg=scene.add.rectangle(0,0,barWidth+4,9,0x160d20,.9).setStrokeStyle(1,0xf3ca79,.85),fill=scene.add.rectangle(-barWidth/2,0,barWidth,5,0xd94b82,1).setOrigin(0,.5);this.healthBarWidth=barWidth;this.healthBarFill=fill;this.healthHud=scene.add.container(x,y-60,[bg,fill]).setDepth(34).setVisible(false);
  }
  enter(state,duration=0){this.state=state;this.stateTime=duration;if(state!==STATES.ATTACK)this.damageActive=false;if(state===STATES.DEAD)this.releaseAttackSlot();}
  acquireAttackSlot(){const slots=this.scene.directAttackers||(this.scene.directAttackers=new Set());if(this.attackSlot)return true;if(slots.size>=3)return false;slots.add(this);this.attackSlot=true;return true;}
  releaseAttackSlot(){if(this.attackSlot)this.scene.directAttackers?.delete(this);this.attackSlot=false;}
  canAct(){return this.active&&this.body?.enable&&this.visible&&this.alpha>=.45;}
  update(delta=16){
    if(!this.canAct()||this.state===STATES.DEAD)return;if(this.inAction){this.setVelocityX(0);return;}const player=this.scene.player;if(!player)return;this.stateTime-=delta;this.attackCooldown=Math.max(0,this.attackCooldown-delta);this.aggroUntil=Math.max(0,this.aggroUntil-delta);this.staggerCooldown=Math.max(0,this.staggerCooldown-delta);this.stepCooldown=Math.max(0,this.stepCooldown-delta);const playerDx=player.x-this.x,dist=Math.abs(playerDx),verticalDist=Math.abs(player.y-this.y),detect=this.miniBoss?920:this.ranged?740:680,verticalDetect=this.flying?300:90,seesPlayer=dist<=detect&&verticalDist<verticalDetect;if(seesPlayer){if(this.aggroUntil===0)this.showAlert();this.aggroUntil=2800;this.lastKnownPlayerX=player.x;}const pursuing=seesPlayer||this.aggroUntil>0,targetX=pursuing?this.lastKnownPlayerX:player.x,dx=targetX-this.x;if(pursuing&&Math.abs(dx)>3)this.direction=Math.sign(dx);this.setFlipX(this.direction<0);
    if(this.state===STATES.HURT){this.setVelocityX(0);if(this.stateTime<=0)this.enter(STATES.RECOVER,240);return;}
    if(this.state===STATES.TELEGRAPH||this.state===STATES.ATTACK||(!this.flying&&this.state===STATES.RECOVER)){if(this.stateTime<=0)this.advanceAction(player);return;}
    if(this.flying){this.updateFlying(player,dist,delta);return;}
    if(!pursuing){this.enter(STATES.PATROL);this.patrol();}
    else if(this.ranged){const ideal=this.type==='mage'?220:190;if(dist<ideal-45){this.enter(STATES.REPOSITION);this.setVelocityX(-this.direction*this.speed*.82);}else if(dist>ideal+35){this.enter(STATES.CHASE);this.setVelocityX(this.direction*this.speed*.95);}else{this.setVelocityX(0);if(this.attackCooldown<=0)this.beginTelegraph('ranged');}}
    else if(dist>70){const factor=this.miniBoss ? 1.4 : this.type==='assassin' ? 1.65 : (this.type==='knight'||this.type==='guardian') ? .9 : 1.15;this.enter(STATES.CHASE);this.setVelocityX(this.direction*this.speed*factor);}
    else if(this.attackCooldown<=0&&this.acquireAttackSlot())this.beginTelegraph(this.miniBoss?this.nextGeneralMove():'melee');else{this.enter(STATES.REPOSITION);this.setVelocityX(-this.direction*this.speed*.35);}
    this.keepInPatrol();if(pursuing&&this.stepCooldown<=0&&this.body.blocked.down&&(this.body.blocked.left||this.body.blocked.right)){this.stepCooldown=700;this.setVelocityY(-285);}this.animateLocomotion();
  }
  patrol(){if(this.x<=this.patrolMinX+3)this.direction=1;if(this.x>=this.patrolMaxX-3)this.direction=-1;this.setVelocityX(this.direction*this.speed*.45);}
  showAlert(){if(this.alertFx?.active)return;this.alertFx=this.scene.add.text(Math.round(this.x),Math.round(this.y-70),'!',{fontFamily:'monospace',fontSize:'22px',color:'#fff0a0',stroke:'#6d1f4c',strokeThickness:4}).setOrigin(.5).setDepth(31);this.scene.tweens.add({targets:this.alertFx,y:this.alertFx.y-13,alpha:0,duration:520,ease:'Cubic.easeOut',onComplete:()=>{this.alertFx?.destroy();this.alertFx=null;}});}
  keepInPatrol(){if(this.x<this.minX){this.x=this.minX;this.direction=1;}if(this.x>this.maxX){this.x=this.maxX;this.direction=-1;}}
  nextGeneralMove(){return ['melee','charge','leap','heavy','summon'][this.generalMove++%5];}
  beginTelegraph(kind){this.actionKind=kind;this.setVelocityX(0);const duration=kind==='heavy'?620:kind==='charge'?480:kind==='leap'?520:kind==='summon'?700:kind==='ranged'?520:kind==='dive'?560:360;this.enter(STATES.TELEGRAPH,duration);if(this.hasEnemySheet)this.setFrame(this.spriteRow*6+2);this.setTint(kind==='heavy'?0xffaa66:kind==='ranged'?0xd98cff:0xff9bbb);const symbol=kind==='ranged'?'✦':kind==='charge'?'➜':kind==='leap'?'⌃':kind==='summon'?'♢':kind==='dive'?'▼':'!';this.attackFx=this.scene.add.text(this.x,this.y-62,symbol,{fontFamily:'monospace',fontSize:kind==='heavy'?'30px':'22px',color:'#fff2b0',stroke:'#6d1f4c',strokeThickness:4}).setOrigin(.5).setDepth(30);this.scene.tweens.add({targets:this.attackFx,y:this.attackFx.y-8,scale:1.2,duration:180,yoyo:true,repeat:-1});}
  advanceAction(player){if(this.state===STATES.TELEGRAPH){this.attackFx?.destroy();this.attackFx=null;this.clearTint();this.enter(STATES.ATTACK,this.actionKind==='charge'?400:this.actionKind==='leap'?500:this.actionKind==='dive'?620:this.actionKind==='heavy'?320:250);this.performAttack(player);return;}if(this.state===STATES.ATTACK){this.damageActive=false;this.enter(STATES.RECOVER,this.miniBoss?390:this.ranged?460:320);this.setVelocityX(0);return;}if(this.state===STATES.RECOVER){this.releaseAttackSlot();this.attackCooldown=this.miniBoss?520:this.type==='assassin'?560:this.ranged?720:680;this.enter(STATES.REPOSITION,180);}}
  performAttack(player){if(!this.canAct())return;if(this.actionKind==='ranged'){this.spawnProjectile(player);return;}if(this.actionKind==='summon'){this.summonHelpers();return;}if(this.actionKind==='dive'){this.performDive();return;}if(this.actionKind==='leap')this.setVelocity(this.direction*170,-330);else if(this.actionKind==='charge')this.setVelocityX(this.direction*320);else this.setVelocityX(this.direction*(this.actionKind==='heavy'?135:210));this.damageActive=true;if(this.hasEnemySheet)this.setFrame(this.spriteRow*6+3);}
  updateFlying(player,dist,delta){this.body.setAllowGravity(false);if(this.state===STATES.RECOVER){this.damageActive=false;this.x=Phaser.Math.Linear(this.x,this.spawnX,.035);this.y=Phaser.Math.Linear(this.y,this.startY,.055);this.body.updateFromGameObject();if(this.stateTime<=0){this.releaseAttackSlot();this.attackCooldown=1050;this.enter(STATES.PATROL);}return;}this.y=this.startY+Math.sin(this.scene.time.now/420+this.spawnX*.01)*18;this.x+=this.direction*this.speed*.22*delta/1000;if(this.x<this.minX||this.x>this.maxX)this.direction*=-1;this.body.updateFromGameObject();if(dist<420&&this.attackCooldown<=0&&this.acquireAttackSlot()){this.diveTarget={x:player.x,y:player.y};this.beginTelegraph('dive');}}
  performDive(){const target=this.diveTarget||this.scene.player,angle=Phaser.Math.Angle.Between(this.x,this.y,target.x,target.y);this.setVelocity(Math.cos(angle)*420,Math.sin(angle)*420);this.damageActive=true;}
  spawnProjectile(player){const key=this.type==='mage'||this.type==='magic'?'enemy-magic-orb':'enemy-feather-shot',orb=this.scene.add.image(this.x+this.direction*22,this.y-12,key).setName(key).setDepth(19);this.scene.physics.add.existing(orb);orb.body.setAllowGravity(false);orb.body.setSize(Math.min(24,orb.width*.72),Math.min(24,orb.height*.72),true);const angle=Phaser.Math.Angle.Between(orb.x,orb.y,player.x,player.y);orb.setRotation(angle);orb.body.setVelocity(Math.cos(angle)*270,Math.sin(angle)*270);let hit=null,wallHit=null,finished=false;const destroyProjectile=()=>{if(finished)return;finished=true;if(hit?.active)hit.destroy();if(wallHit?.active)wallHit.destroy();if(orb.active)orb.destroy();};hit=this.scene.physics.add.overlap(player,orb,()=>{player.takeDamage(1,orb);destroyProjectile();});wallHit=this.scene.physics.add.collider(orb,this.scene.solids,destroyProjectile);this.scene.time.delayedCall(2200,destroyProjectile);}
  summonHelpers(){const alive=this.scene.enemies?.getChildren().filter(e=>e.active&&e.summonedBy===this).length||0;for(let i=alive;i<2;i++){const helper=new this.constructor(this.scene,this.x+(i?90:-90),this.y-100,{type:'winged',health:2,minX:this.x-240,maxX:this.x+240,speed:105});helper.summonedBy=this;this.scene.enemies.add(helper);}}
  animateLocomotion(){if(!this.humanoid)return;const base=this.hasEnemySheet?(this.miniBoss?0.82:0.66):(this.miniBoss?1.25:1.05);this.setScale(base);this.setPosition(Math.round(this.x),Math.round(this.y));if(this.hasEnemySheet)this.setFrame(this.spriteRow*6+(Math.abs(this.body.velocity.x)>10?1+Math.floor(this.scene.time.now/190)%2:0));if(this.roleTint!==0xffffff)this.setTint(this.roleTint);}
  showCombatText(text,color='#ffffff'){const fx=this.scene.add.text(Math.round(this.x),Math.round(this.y-64),text,{fontFamily:'monospace',fontSize:'13px',color,stroke:'#281426',strokeThickness:3}).setOrigin(.5).setDepth(35);this.scene.tweens.add({targets:fx,y:fx.y-24,alpha:0,duration:520,onComplete:()=>fx.destroy()});}
  syncHealthHud(){if(!this.healthHud)return;const visible=!this.miniBoss&&this.active&&this.visible&&this.alpha>=.45&&(this.aggroUntil>0||this.health<this.maxHealth);this.healthHud.setVisible(visible).setPosition(Math.round(this.x),Math.round(this.y-62));if(!visible)return;const ratio=Phaser.Math.Clamp(this.health/this.maxHealth,0,1);this.healthBarFill.displayWidth=this.healthBarWidth*ratio;this.healthBarFill.setFillStyle(ratio>.55?0xd94b82:ratio>.25?0xe19b4d:0xe45353);}
  hit(amount=1,knockback=0){if(!this.canAct()||this.state===STATES.DEAD)return;this.health-=amount;this.showCombatText(`-${amount}`,'#fff0a6');const stagger=this.staggerCooldown<=0;if(stagger){this.staggerCooldown=this.miniBoss?1150:650;this.releaseAttackSlot();this.enter(STATES.HURT,this.miniBoss?120:165);if(this.hasEnemySheet)this.setFrame(this.spriteRow*6+4);this.setVelocityX((knockback||-this.direction*120)*(this.miniBoss ? .45 : 1));}this.setTintFill(0xffffff);this.scene.audioManager?.playSfx('enemyDown');this.scene.particleManager?.sparkles(this.x,this.y,0xff8fc8,7);this.scene.time.delayedCall(90,()=>{if(!this.active)return;this.clearTint();if(this.roleTint!==0xffffff)this.setTint(this.roleTint);});if(this.health<=0)this.die();}
  die(){this.enter(STATES.DEAD);this.attackFx?.destroy();this.alertFx?.destroy();this.healthHud?.destroy();this.healthHud=null;this.scene.onRuneGuardianDefeated?.(this);this.scene.particleManager?.burst(this.x,this.y,0xffd7f6,18,200);this.body.enable=false;if(this.hasEnemySheet)this.setFrame(this.spriteRow*6+5);this.scene.tweens.add({targets:this,y:this.y+18,angle:this.hasEnemySheet?0:90,alpha:0,duration:480,delay:120,onComplete:()=>this.disableBody(true,true)});this.scene.addRose?.(1);}
}
